
export const allTools = [
    { key: "prophets", icon: "👨‍👩‍👧‍👦", de: "25 Propheten", en: "25 Prophets", href: "/prophets" },
    { key: "arabic_basics", icon: "✍️", de: "Arabische Grundlagen", en: "Arabic Basics", href: "/arabic-basics" },
    { key: "arabic_numbers", icon: "🔢", de: "Arabische Zahlen", en: "Arabic Numbers", href: "/arabic-numbers" },
    { key: "asmaul_husna", icon: "🙌", de: "Asma-Ul Husna", en: "Asma-Ul Husna", href: "/asma-ul-husna" },
    { key: "memorization", icon: "🧠", de: "Auswendiglernen", en: "Memorization", href: "/memorization" },
    { key: "community", icon: "🎉", de: "Community & Events", en: "Community & Events", href: "/community" },
    { key: "favorites", icon: "⭐", de: "Deine Favoriten", en: "Your Favorites", href: "/favorites" },
    { key: "dhikr", icon: "🙏", de: "Dhikr & Bittgebete", en: "Dhikr & Supplications", href: "/dhikr" },
    { key: "rays_of_islam", icon: "✨", de: "Die Strahlen Des Islam", en: "The Rays Of Islam", href: "/rays-of-islam" },
    { key: "dua_generator", icon: "🤖", de: "Du'a-Generator", en: "Du'a Generator", description: "KI generiert für verschiedene Zwecke und Anlässe Du'a", href: "/dua-generator" },
    { key: "dua", icon: "🤲", de: "Dua", en: "Dua", href: "/dua" },
    { key: "nikah", icon: "💍", de: "Ehe (Nikah)", en: "Marriage (Nikah)", href: "/nikah" },
    { key: "reminders", icon: "🔔", de: "Erinnerungen", en: "Reminders", href: "/reminders" },
    { key: "food_rules", icon: "🍽️", de: "Essensregeln", en: "Food Rules", href: "/food-rules" },
    { key: "finance", icon: "💰", de: "Finanzen", en: "Finances", href: "/finances" },
    { key: "prayer_on_time", icon: "⏳", de: "Gebet auf Zeit", en: "Prayer on Time", href: "/prayer-on-time" },
    { key: "wudu", icon: "💧", de: "Gebetswaschung (Wudu)", en: "Ablution (Wudu)", href: "/wudu" },
    { key: "prayer_times", icon: "🌙", de: "Gebetszeiten", en: "Prayer Times", href: "/prayer-times" },
    { key: "greeting_card", icon: "💌", de: "Grußkarte", en: "Greeting Card", href: "/greeting-card" },
    { key: "akhlaq", icon: "😊", de: "Gute Manieren (Akhlaq)", en: "Good Manners (Akhlaq)", href: "/akhlaq" },
    { key: "hadith", icon: "📚", de: "Hadith Sammlung", en: "Hadith Collection", href: "/hadith" },
    { key: "hadith_of_day", icon: "📜", de: "Hadith des Tages", en: "Hadith of the Day", href: "/hadith-of-the-day" },
    { key: "ai_scholar", icon: "🤖", de: "KI-Gelehrter", en: "AI Scholar", href: "/halal-haram-checker" },
    { key: "hatim", icon: "📖", de: "Hatim", en: "Hatim", href: "/hatim" },
    { key: "quran", icon: "📖", de: "Heiliger Koran", en: "Holy Quran", href: "/quran" },
    { key: "hijri_converter", icon: "🔄", de: "Hijri Konverter", en: "Hijri Converter", href: "/hijri-converter" },
    { key: "hisnul_muslim", icon: "🛡️", de: "Hisnul Muslim", en: "Hisnul Muslim", href: "/hisnul-muslim" },
    { key: "islamic_education", icon: "🎓", de: "Islamische Erziehung", en: "Islamic Education", href: "/islamic-education" },
    { key: "islamic_stories", icon: "📜", de: "Islamische Geschichten", en: "Islamic Stories", href: "/islamic-stories" },
    { key: "islamic_art", icon: "🎨", de: "Islamische Kunst", en: "Islamic Art", href: "/islamic-art" },
    { key: "islamic_fashion", icon: "👚", de: "Islamische Mode", en: "Islamic Fashion", href: "/islamic-fashion" },
    { key: "islamic_months", icon: "🌙", de: "Islamische Monate", en: "Islamic Months", href: "/islamic-months" },
    { key: "islamic_names", icon: "👶", de: "Islamische Namen", en: "Islamic Names", href: "/islamic-names" },
    { key: "islamic_miracles", icon: "🌟", de: "Wunder im Islam", en: "Miracles in Islam", href: "/islamic-miracles" },
    { key: "islamic_quotes", icon: "💬", de: "Islamische Zitate", en: "Islamic Quotes", href: "/islamic-quotes" },
    { key: "islamic_calendar", icon: "📅", de: "Islamischer Kalender", en: "Islamic Calendar", href: null },
    { key: "khutbah_of_week", icon: "🎤", de: "Khutbah der Woche", en: "Khutbah of the Week", href: null },
    { key: "compass", icon: "🧭", de: "Kompass", en: "Compass", href: null },
    { key: "reverts_corner", icon: "🤝", de: "Konvertiten-Ecke", en: "Revert's Corner", href: null },
    { key: "quran_recognizer", icon: "🔍", de: "Koran-Erkenner", en: "Quran Recognizer", href: null },
    { key: "verse_of_day", icon: "📜", de: "Koranvers des Tages", en: "Verse of the Day", href: null },
    { key: "ladies_special", icon: "👩", de: "Ladies Special", en: "Ladies Special", href: null },
    { key: "learning_path_generator", icon: "🗺️", de: "Lernpfad-Generator", en: "Learning Path Generator", href: null },
    { key: "mosque_finder", icon: "🕌", de: "Moscheefinder", en: "Mosque Finder", href: null },
    { key: "prophetic_medicine", icon: "🌿", de: "Prophetische Medizin", en: "Prophetic Medicine", href: null },
    { key: "qibla", icon: "🕋", de: "Qibla", en: "Qibla", href: null },
    { key: "quiz", icon: "❓", de: "Quiz", en: "Quiz", href: null },
    { key: "radio", icon: "📻", de: "Radio", en: "Radio", href: null },
    { key: "travel_etiquette", icon: "✈️", de: "Reise-Etikette", en: "Travel Etiquette", href: null },
    { key: "sahaba", icon: "👥", de: "Sahaba", en: "Sahaba", href: null },
    { key: "donations", icon: "💸", de: "Spenden", en: "Donations", href: null },
    { key: "tasbih_counter", icon: "📿", de: "Tasbih Zähler", en: "Tasbih Counter", href: null },
    { key: "janazah", icon: "⚰️", de: "Todesfall (Janazah)", en: "Death (Janazah)", href: null },
    { key: "dream_interpreter", icon: "🌙", de: "Traumdeuter", en: "Dream Interpreter", href: null },
    { key: "dreams_in_islam", icon: "💤", de: "Träume im Islam", en: "Dreams in Islam", href: null },
    { key: "support", icon: "❤️", de: "Unterstützung", en: "Support", href: null },
    { key: "missed_fasts", icon: "🗓️", de: "Verpasste Fastentage", en: "Missed Fasts", href: null },
    { key: "missed_prayers", icon: " نماز", de: "Verpasste Gebete", en: "Missed Prayers", href: null },
    { key: "verse_finder", icon: "🔎", de: "Vers-Finder", en: "Verse Finder", href: null },
    { key: "quran_miracles", icon: "✨", de: "Wunder des Korans", en: "Miracles of the Quran", href: null },
    { key: "zakat_calculator", icon: "💸", de: "Zakat-Rechner", en: "Zakat Calculator", href: null },
    { key: "civilization", icon: "🏛️", de: "Zivilisation", en: "Civilization", href: null }
];
